apiVersion: v1
kind: Service
metadata:
  name: timescaledb-service
  namespace: llm-ns
spec:
  selector:
    app: timescaledb
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP